//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.02 at 10:07:22 AM MSK 
//


package com.ipc.oce.events.v81;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}Level" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}Date" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}ApplicationName" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}ApplicationPresentation" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}EventName" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}EventPresentation" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}UserID" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}UserName" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}Computer" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}MetadataName" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}MetadataPresentation" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}Comment" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}Data" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}DataPresentation" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}TransactionStatus" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}TransactionID" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}Connection" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}ServerName" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}Port" minOccurs="0"/>
 *         &lt;element ref="{http://v8.1c.ru/eventLog}SyncPort" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType", propOrder = {
    "level",
    "date",
    "applicationName",
    "applicationPresentation",
    "eventName",
    "eventPresentation",
    "userID",
    "userName",
    "computer",
    "metadataName",
    "metadataPresentation",
    "comment",
    "data",
    "dataPresentation",
    "transactionStatus",
    "transactionID",
    "connection",
    "serverName",
    "port",
    "syncPort"
})
public class EventType {

    @XmlElement(name = "Level")
    protected String level;
    @XmlElement(name = "Date")
    protected String date;
    @XmlElement(name = "ApplicationName")
    protected String applicationName;
    @XmlElement(name = "ApplicationPresentation")
    protected String applicationPresentation;
    @XmlElement(name = "EventName")
    protected String eventName;
    @XmlElement(name = "EventPresentation")
    protected String eventPresentation;
    @XmlElement(name = "UserID")
    protected String userID;
    @XmlElement(name = "UserName")
    protected String userName;
    @XmlElement(name = "Computer")
    protected String computer;
    @XmlElement(name = "MetadataName")
    protected String metadataName;
    @XmlElement(name = "MetadataPresentation")
    protected String metadataPresentation;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "Data")
    protected String data;
    @XmlElement(name = "DataPresentation")
    protected String dataPresentation;
    @XmlElement(name = "TransactionStatus")
    protected String transactionStatus;
    @XmlElement(name = "TransactionID")
    protected String transactionID;
    @XmlElement(name = "Connection")
    protected String connection;
    @XmlElement(name = "ServerName")
    protected String serverName;
    @XmlElement(name = "Port")
    protected Integer port;
    @XmlElement(name = "SyncPort")
    protected Integer syncPort;

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the applicationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * Sets the value of the applicationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationName(String value) {
        this.applicationName = value;
    }

    /**
     * Gets the value of the applicationPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationPresentation() {
        return applicationPresentation;
    }

    /**
     * Sets the value of the applicationPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationPresentation(String value) {
        this.applicationPresentation = value;
    }

    /**
     * Gets the value of the eventName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventName(String value) {
        this.eventName = value;
    }

    /**
     * Gets the value of the eventPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventPresentation() {
        return eventPresentation;
    }

    /**
     * Sets the value of the eventPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventPresentation(String value) {
        this.eventPresentation = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the computer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComputer() {
        return computer;
    }

    /**
     * Sets the value of the computer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComputer(String value) {
        this.computer = value;
    }

    /**
     * Gets the value of the metadataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataName() {
        return metadataName;
    }

    /**
     * Sets the value of the metadataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataName(String value) {
        this.metadataName = value;
    }

    /**
     * Gets the value of the metadataPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataPresentation() {
        return metadataPresentation;
    }

    /**
     * Sets the value of the metadataPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataPresentation(String value) {
        this.metadataPresentation = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the dataPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataPresentation() {
        return dataPresentation;
    }

    /**
     * Sets the value of the dataPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataPresentation(String value) {
        this.dataPresentation = value;
    }

    /**
     * Gets the value of the transactionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * Sets the value of the transactionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionStatus(String value) {
        this.transactionStatus = value;
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the connection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnection(String value) {
        this.connection = value;
    }

    /**
     * Gets the value of the serverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * Sets the value of the serverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerName(String value) {
        this.serverName = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPort(Integer value) {
        this.port = value;
    }

    /**
     * Gets the value of the syncPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSyncPort() {
        return syncPort;
    }

    /**
     * Sets the value of the syncPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSyncPort(Integer value) {
        this.syncPort = value;
    }

}
