//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.02 at 10:07:22 AM MSK 
//


package com.ipc.oce.events.v81;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ipc.oce.events.v81 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _SyncPort_QNAME = new QName("http://v8.1c.ru/eventLog", "SyncPort");
    private static final QName _MetadataName_QNAME = new QName("http://v8.1c.ru/eventLog", "MetadataName");
    private static final QName _DataPresentation_QNAME = new QName("http://v8.1c.ru/eventLog", "DataPresentation");
    private static final QName _ServerName_QNAME = new QName("http://v8.1c.ru/eventLog", "ServerName");
    private static final QName _Connection_QNAME = new QName("http://v8.1c.ru/eventLog", "Connection");
    private static final QName _UserName_QNAME = new QName("http://v8.1c.ru/eventLog", "UserName");
    private static final QName _Comment_QNAME = new QName("http://v8.1c.ru/eventLog", "Comment");
    private static final QName _Computer_QNAME = new QName("http://v8.1c.ru/eventLog", "Computer");
    private static final QName _UserID_QNAME = new QName("http://v8.1c.ru/eventLog", "UserID");
    private static final QName _Event_QNAME = new QName("http://v8.1c.ru/eventLog", "Event");
    private static final QName _ApplicationPresentation_QNAME = new QName("http://v8.1c.ru/eventLog", "ApplicationPresentation");
    private static final QName _ApplicationName_QNAME = new QName("http://v8.1c.ru/eventLog", "ApplicationName");
    private static final QName _EventName_QNAME = new QName("http://v8.1c.ru/eventLog", "EventName");
    private static final QName _EventPresentation_QNAME = new QName("http://v8.1c.ru/eventLog", "EventPresentation");
    private static final QName _EventLog_QNAME = new QName("http://v8.1c.ru/eventLog", "EventLog");
    private static final QName _Level_QNAME = new QName("http://v8.1c.ru/eventLog", "Level");
    private static final QName _MetadataPresentation_QNAME = new QName("http://v8.1c.ru/eventLog", "MetadataPresentation");
    private static final QName _Date_QNAME = new QName("http://v8.1c.ru/eventLog", "Date");
    private static final QName _Port_QNAME = new QName("http://v8.1c.ru/eventLog", "Port");
    private static final QName _TransactionID_QNAME = new QName("http://v8.1c.ru/eventLog", "TransactionID");
    private static final QName _TransactionStatus_QNAME = new QName("http://v8.1c.ru/eventLog", "TransactionStatus");
    private static final QName _Data_QNAME = new QName("http://v8.1c.ru/eventLog", "Data");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ipc.oce.events.v81
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EventLogType }
     * 
     */
    public EventLogType createEventLogType() {
        return new EventLogType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "SyncPort")
    public JAXBElement<Integer> createSyncPort(Integer value) {
        return new JAXBElement<Integer>(_SyncPort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "MetadataName")
    public JAXBElement<String> createMetadataName(String value) {
        return new JAXBElement<String>(_MetadataName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "DataPresentation")
    public JAXBElement<String> createDataPresentation(String value) {
        return new JAXBElement<String>(_DataPresentation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "ServerName")
    public JAXBElement<String> createServerName(String value) {
        return new JAXBElement<String>(_ServerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "Connection")
    public JAXBElement<String> createConnection(String value) {
        return new JAXBElement<String>(_Connection_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "UserName")
    public JAXBElement<String> createUserName(String value) {
        return new JAXBElement<String>(_UserName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "Comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "Computer")
    public JAXBElement<String> createComputer(String value) {
        return new JAXBElement<String>(_Computer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "UserID")
    public JAXBElement<String> createUserID(String value) {
        return new JAXBElement<String>(_UserID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "Event")
    public JAXBElement<EventType> createEvent(EventType value) {
        return new JAXBElement<EventType>(_Event_QNAME, EventType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "ApplicationPresentation")
    public JAXBElement<String> createApplicationPresentation(String value) {
        return new JAXBElement<String>(_ApplicationPresentation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "ApplicationName")
    public JAXBElement<String> createApplicationName(String value) {
        return new JAXBElement<String>(_ApplicationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "EventName")
    public JAXBElement<String> createEventName(String value) {
        return new JAXBElement<String>(_EventName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "EventPresentation")
    public JAXBElement<String> createEventPresentation(String value) {
        return new JAXBElement<String>(_EventPresentation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventLogType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "EventLog")
    public JAXBElement<EventLogType> createEventLog(EventLogType value) {
        return new JAXBElement<EventLogType>(_EventLog_QNAME, EventLogType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "Level")
    public JAXBElement<String> createLevel(String value) {
        return new JAXBElement<String>(_Level_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "MetadataPresentation")
    public JAXBElement<String> createMetadataPresentation(String value) {
        return new JAXBElement<String>(_MetadataPresentation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "Date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "Port")
    public JAXBElement<Integer> createPort(Integer value) {
        return new JAXBElement<Integer>(_Port_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "TransactionID")
    public JAXBElement<String> createTransactionID(String value) {
        return new JAXBElement<String>(_TransactionID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "TransactionStatus")
    public JAXBElement<String> createTransactionStatus(String value) {
        return new JAXBElement<String>(_TransactionStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://v8.1c.ru/eventLog", name = "Data")
    public JAXBElement<String> createData(String value) {
        return new JAXBElement<String>(_Data_QNAME, String.class, null, value);
    }

}
