//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.02 at 10:07:22 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://v8.1c.ru/eventLog", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ipc.oce.events.v81;
